/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImperessumRouteImport } from './routes/imperessum'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizCategoryIdRouteImport } from './routes/quiz/$categoryId'

const ImperessumRoute = ImperessumRouteImport.update({
  id: '/imperessum',
  path: '/imperessum',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCategoryIdRoute = QuizCategoryIdRouteImport.update({
  id: '/quiz/$categoryId',
  path: '/quiz/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/imperessum': typeof ImperessumRoute
  '/quiz/$categoryId': typeof QuizCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/imperessum': typeof ImperessumRoute
  '/quiz/$categoryId': typeof QuizCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/imperessum': typeof ImperessumRoute
  '/quiz/$categoryId': typeof QuizCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/imperessum' | '/quiz/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/imperessum' | '/quiz/$categoryId'
  id: '__root__' | '/' | '/about' | '/imperessum' | '/quiz/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ImperessumRoute: typeof ImperessumRoute
  QuizCategoryIdRoute: typeof QuizCategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/imperessum': {
      id: '/imperessum'
      path: '/imperessum'
      fullPath: '/imperessum'
      preLoaderRoute: typeof ImperessumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$categoryId': {
      id: '/quiz/$categoryId'
      path: '/quiz/$categoryId'
      fullPath: '/quiz/$categoryId'
      preLoaderRoute: typeof QuizCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ImperessumRoute: ImperessumRoute,
  QuizCategoryIdRoute: QuizCategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
